#include "/Engine/Public/Platform.ush"

int2 OutputSize;
RWTexture2D<float4> OutputTexture;

[numthreads(8, 8, 1)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
    if (any(DispatchThreadId.xy >= OutputSize))
    {
        return;
    }

    float2 uv =
        (float2(DispatchThreadId.xy) + 0.5) /
        float2(OutputSize);

    OutputTexture[DispatchThreadId.xy] =
        float4(uv.x, uv.y, 1.0, 1.0);
}